[package]
name = "messaging"
version = "0.0.1"

[dependencies]
Iota = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "testnet" }

[addresses]
messaging = "0x0"  # <--- Hier muss 0x0 stehen!
