/**
 * Flache Core-Rückgabe + messengerPorts aus Sub-Hook-Slices (Orchestrator bleibt dünn).
 */

import { assembleChatViewMessengerPorts, type ChatViewMessengerPorts } from '@/frontend/features/messenger-ports'
import type { MessengerChatChannel } from '@/frontend/lib/messenger-chat-channel'
import type { MessengerGroupDefinition } from '@/frontend/lib/messenger-group-store'
import type { ChatViewComposerTransportState } from '@/frontend/hooks/use-chat-view-composer-transport-state'
import type { ChatViewInboxOrchestration } from '@/frontend/hooks/use-chat-view-inbox-orchestration'
import type { ChatViewSendOrchestration } from '@/frontend/hooks/use-chat-view-send-orchestration'

export type BuildChatViewCoreStateInput = {
  channelMode: MessengerChatChannel
  role: string
  myAddress: string
  isGroup: boolean
  activeGroup: MessengerGroupDefinition | null
  refreshMessengerGroups: () => void
  composer: ChatViewComposerTransportState
  inbox: ChatViewInboxOrchestration
  send: ChatViewSendOrchestration
}

export function buildChatViewCoreMessengerPorts(
  composer: ChatViewComposerTransportState,
  inbox: ChatViewInboxOrchestration,
  send: ChatViewSendOrchestration,
  myAddress: string
): ChatViewMessengerPorts {
  return assembleChatViewMessengerPorts({
    composerDraft: {
      message: composer.message,
      recipient: composer.recipient,
      setMessage: composer.setMessage,
      setRecipient: composer.setRecipient,
    },
    transport: {
      encrypted: composer.encrypted,
      setEncrypted: composer.setEncrypted,
      forcedTransport: composer.forcedTransport,
      setForcedTransport: composer.setForcedTransport,
      messagingPersistenceMode: composer.messagingPersistenceMode,
      setMessagingPersistenceMode: composer.setMessagingPersistenceMode,
    },
    meshFunk: {
      meshLoRaImagesEnabled: composer.meshLoRaImagesEnabled,
      setMeshLoRaImagesEnabled: composer.setMeshLoRaImagesEnabled,
      meshSelfArchiveAfterLoRa: composer.meshSelfArchiveAfterLoRa,
      setMeshSelfArchiveAfterLoRa: composer.setMeshSelfArchiveAfterLoRa,
    },
    inboxFeed: {
      messages: inbox.displayMessages,
      myAddress,
    },
    voiceFromHook: {
      voicePhase: send.voicePhase,
      voiceActiveKind: send.voiceActiveKind,
      voiceProgress01: send.voiceProgress01,
      voiceMaxSeconds: send.voiceMaxSeconds,
      voiceEmergencyMaxSeconds: send.voiceEmergencyMaxSeconds,
      sosVoiceFollowsOnline: send.sosVoiceFollowsOnline,
      onVoiceToggle: send.onVoiceToggle,
      onVoiceEmergencyToggle: send.onVoiceEmergencyToggle,
      voiceNormalBlockedStart: send.voiceNormalBlockedStart,
      voiceEmergencyBlockedStart: send.voiceEmergencyBlockedStart,
      voiceBusy: send.voiceBusy,
      voiceRecording: send.voiceRecording,
    },
    sosVoiceAwaitingSend: send.sosVoiceAwaitingSend,
  })
}

export function buildChatViewCoreState(input: BuildChatViewCoreStateInput) {
  const { channelMode, role, myAddress, isGroup, activeGroup, refreshMessengerGroups, composer, inbox, send } =
    input
  const messengerPorts = buildChatViewCoreMessengerPorts(composer, inbox, send, myAddress)

  return {
    channelMode,
    isPrivate: composer.isPrivate,
    isGroup,
    activeGroup,
    refreshMessengerGroups,
    role,
    myAddress,
    messengerPorts,
    message: composer.message,
    setMessage: composer.setMessage,
    recipient: composer.recipient,
    setRecipient: composer.setRecipient,
    partner: composer.partner,
    setPartner: composer.setPartner,
    sending: composer.sending,
    setSending: composer.setSending,
    status: composer.status,
    statusMsg: composer.statusMsg,
    setStatus: composer.setStatus,
    setStatusMsg: composer.setStatusMsg,
    showSetup: composer.showSetup,
    setShowSetup: composer.setShowSetup,
    toggleShowSetup: send.toggleShowSetup,
    encrypted: composer.encrypted,
    setEncrypted: composer.setEncrypted,
    apiStatus: inbox.apiStatus,
    refreshApiStatus: inbox.refreshApiStatus,
    basisUnreachable: inbox.basisUnreachable,
    statusCacheAgeMinutes: inbox.statusCacheAgeMinutes,
    packageIdMismatch: inbox.packageIdMismatch,
    deviceTimeTrustWarn: inbox.deviceTimeTrustWarn,
    syncCanonicalPackageIdFromServer: inbox.syncCanonicalPackageIdFromServer,
    mirrorQueuePending: inbox.mirrorQueuePending,
    offlineMailboxQueuePending: inbox.offlineMailboxQueuePending,
    offlineMailboxQueueUntrustedTimeCount: inbox.offlineMailboxQueueUntrustedTimeCount,
    offlineMailboxQueueBackoffCount: inbox.offlineMailboxQueueBackoffCount,
    offlineMailboxQueueErrorHint: inbox.offlineMailboxQueueErrorHint,
    offlineMailboxQueueItems: inbox.offlineMailboxQueueItems,
    removeOfflineMailboxQueueItems: inbox.removeOfflineMailboxQueueItems,
    inboxPackageFilter: inbox.inboxPackageFilter,
    setInboxPackageFilter: inbox.setInboxPackageFilter,
    packageIdSuggestions: inbox.packageIdSuggestions,
    refreshPackageIdSuggestions: inbox.refreshPackageIdSuggestions,
    applyPackageIdBackend: inbox.applyPackageIdBackend,
    applyInboxPackageFilterOnly: inbox.applyInboxPackageFilterOnly,
    packageIdBusy: inbox.packageIdBusy,
    forcedTransport: composer.forcedTransport,
    setForcedTransport: composer.setForcedTransport,
    composerDelivery: composer.composerDelivery,
    setComposerDelivery: composer.setComposerDelivery,
    meshtasticChannelIndex: composer.meshtasticChannelIndex,
    setMeshtasticChannelIndex: composer.setMeshtasticChannelIndex,
    messagingPersistenceMode: composer.messagingPersistenceMode,
    setMessagingPersistenceMode: composer.setMessagingPersistenceMode,
    composerMailboxObjectId: composer.composerMailboxObjectId,
    setComposerMailboxObjectId: composer.setComposerMailboxObjectId,
    morgPkgDeviceBusy: composer.morgPkgDeviceBusy,
    morgPkgFileRef: composer.morgPkgFileRef,
    morgPkgDeviceFilesRef: composer.morgPkgDeviceFilesRef,
    directory: inbox.directory,
    refreshContactDirectory: inbox.refreshContactDirectory,
    isMeshVerifiedForAddress: inbox.isMeshVerifiedForAddress,
    inboxTotalCount: inbox.filteredDisplayMessages.length,
    messages: inbox.displayMessages,
    setMessages: inbox.setMessages,
    loading: inbox.loading,
    loadingMore: inbox.loadingMore,
    loadError: inbox.loadError,
    inboxFromCache: inbox.inboxFromCache,
    inboxCacheAgeMinutes: inbox.inboxCacheAgeMinutes,
    inboxLiveSource: inbox.inboxLiveSource,
    loadMessages: inbox.loadMessages,
    loadMoreInbox: inbox.loadMoreInbox,
    inboxHasMore: inbox.inboxHasMore,
    appendMeshMessage: inbox.appendMeshMessage,
    clearInboxRam: inbox.clearInboxRam,
    slideSequences: inbox.slideSequences,
    inboxRows: inbox.inboxRows,
    pinnwandFeedMessages: inbox.pinnwandFeedMessages,
    pinnwandInboxRows: inbox.pinnwandInboxRows,
    meshtastic: send.meshtastic,
    meshSyncMsg: send.meshSyncMsg,
    setMeshSyncMsg: send.setMeshSyncMsg,
    localPurgeBusy: send.localPurgeBusy,
    setLocalPurgeBusy: send.setLocalPurgeBusy,
    contactBleAddress: send.contactBleAddress,
    setContactBleAddress: send.setContactBleAddress,
    contactBleUuid: send.contactBleUuid,
    setContactBleUuid: send.setContactBleUuid,
    contactBleBusy: send.contactBleBusy,
    setContactBleBusy: send.setContactBleBusy,
    meshPlaintextToNodeEnabled: send.meshPlaintextToNodeEnabled,
    setMeshPlaintextToNodeEnabled: send.setMeshPlaintextToNodeEnabled,
    meshPlaintextNodeId: send.meshPlaintextNodeId,
    setMeshPlaintextNodeId: send.setMeshPlaintextNodeId,
    attachedBlobBase64: send.attachedBlobBase64,
    attachedTxtFile: send.attachedTxtFile,
    attachedAudioBase64: send.attachedAudioBase64,
    attachedLora: send.attachedLora,
    compactMeta: send.compactMeta,
    compactPreviewUrl: send.compactPreviewUrl,
    loraPreviewUrl: send.loraPreviewUrl,
    loraMeshProgressLine: composer.loraMeshProgressLine,
    loraOnlineFallbackOffer: send.loraOnlineFallbackOffer,
    compactBusy: send.compactBusy,
    attachmentPipelineHint: send.attachmentPipelineHint,
    compactFileRef: send.compactFileRef,
    clearCompactAttachment: send.clearCompactAttachment,
    handleCompactAttachmentPick: send.handleCompactAttachmentPick,
    ingestChatAttachmentFile: send.ingestChatAttachmentFile,
    exportEcdhMorgPkgForMessage: send.exportEcdhMorgPkgForMessage,
    onMorgPkgDeviceFiles: send.onMorgPkgDeviceFiles,
    onMorgPkgImportFile: send.onMorgPkgImportFile,
    onMorgPkgDeviceExportPick: send.onMorgPkgDeviceExportPick,
    morgPkgImports: send.morgPkgImports,
    morgPkgImportsOpen: send.morgPkgImportsOpen,
    setMorgPkgImportsOpen: send.setMorgPkgImportsOpen,
    removeMorgPkgImport: send.removeMorgPkgImport,
    onForwardMorgPkgItem: send.onForwardMorgPkgItem,
    morgPkgExportRecipient: send.morgPkgExportRecipient,
    setMorgPkgExportRecipient: send.setMorgPkgExportRecipient,
    morgPkgExportPartnerOptions: send.morgPkgExportPartnerOptions,
    confirmLoraSendViaOnline: send.confirmLoraSendViaOnline,
    handleSend: send.handleSend,
    cancelSend: send.cancelSend,
    handleHandshake: send.handleHandshake,
    handleHandshakeForAddress: send.handleHandshakeForAddress,
    handleConnectAcceptPartner: send.handleConnectAcceptPartner,
    handleConnectAcceptForAddress: send.handleConnectAcceptForAddress,
    handleConnectDeployment: send.handleConnectDeployment,
    dismissLoraOnlineFallback: send.dismissLoraOnlineFallback,
    openPartnerSetupPanel: send.openPartnerSetupPanel,
    onExportEinsatzberichtJson: inbox.onExportEinsatzberichtJson,
    onExportEinsatzberichtTxt: inbox.onExportEinsatzberichtTxt,
    onExportEinsatzberichtTxtFull: inbox.onExportEinsatzberichtTxtFull,
    onExportEinsatzberichtEncrypted: inbox.onExportEinsatzberichtEncrypted,
    onExportEinsatzprotokoll: inbox.onExportEinsatzprotokoll,
    onExportEinsatzprotokollPlainZip: inbox.onExportEinsatzprotokollPlainZip,
    onExportEinsatzprotokollMarked: inbox.onExportEinsatzprotokollMarked,
    meshLoRaImagesEnabled: composer.meshLoRaImagesEnabled,
    setMeshLoRaImagesEnabled: composer.setMeshLoRaImagesEnabled,
    meshSelfArchiveAfterLoRa: composer.meshSelfArchiveAfterLoRa,
    setMeshSelfArchiveAfterLoRa: composer.setMeshSelfArchiveAfterLoRa,
    protokollMarkedIds: inbox.protokollMarkedIds,
    pinnedPinnwandIds: inbox.pinnedPinnwandIds,
    togglePinnedPinnwand: inbox.togglePinnedPinnwand,
    toggleProtokollMark: inbox.toggleProtokollMark,
    onHideInboxMessageLocal: inbox.onHideInboxMessageLocal,
    onPurgeInboxMessageChain: inbox.onPurgeInboxMessageChain,
    onForwardMessage: send.onForwardMessage,
    onHideAllVisibleLocal: inbox.onHideAllVisibleLocal,
    hiddenInboxCount: inbox.hiddenInboxCount,
    inboxSelectMode: inbox.inboxSelectMode,
    setInboxSelectMode: inbox.setInboxSelectMode,
    selectedInboxIds: inbox.selectedInboxIds,
    toggleInboxSelection: inbox.toggleInboxSelection,
    selectAllVisibleInbox: inbox.selectAllVisibleInbox,
    clearInboxSelection: inbox.clearInboxSelection,
    onBulkHideSelected: inbox.onBulkHideSelected,
    onBulkPurgeSelected: inbox.onBulkPurgeSelected,
    inboxPartnerKey: inbox.inboxPartnerKey,
    setInboxPartnerKey: inbox.setInboxPartnerKey,
    inboxDirectionFilter: inbox.inboxDirectionFilter,
    setInboxDirectionFilter: inbox.setInboxDirectionFilter,
    inboxSourceFilter: inbox.inboxSourceFilter,
    setInboxSourceFilter: inbox.setInboxSourceFilter,
    inboxChannelFiltersArmed: inbox.inboxChannelFiltersArmed,
    setInboxChannelFiltersArmed: inbox.setInboxChannelFiltersArmed,
    inboxWireFiltersArmed: inbox.inboxWireFiltersArmed,
    setInboxWireFiltersArmed: inbox.setInboxWireFiltersArmed,
    inboxPartnerFiltersArmed: inbox.inboxPartnerFiltersArmed,
    setInboxPartnerFiltersArmed: inbox.setInboxPartnerFiltersArmed,
    inboxWireFilter: inbox.inboxWireFilter,
    setInboxWireFilter: inbox.setInboxWireFilter,
    inboxPartnerOptions: inbox.inboxPartnerOptions,
    inboxUnreadThreadOptions: inbox.inboxUnreadThreadOptions,
    isInboxMessageUnread: inbox.isInboxMessageUnread,
    isPinnwandInboxMessage: inbox.isPinnwandInboxMessage,
    selectInboxPartnerForSend: inbox.selectInboxPartnerForSend,
    removeInboxPartnerFromQuickList: inbox.removeInboxPartnerFromQuickList,
    resetInboxViewFilters: inbox.resetInboxViewFilters,
    inboxVisibilityHint: inbox.inboxVisibilityHint,
    inboxOverviewChipsVisible: inbox.inboxOverviewChipsVisible,
    inboxOverviewCategory: inbox.inboxOverviewCategory,
    setInboxOverviewCategory: inbox.setInboxOverviewCategory,
    inboxOverviewUnreadCounts: inbox.inboxOverviewUnreadCounts,
    voicePhase: send.voicePhase,
    voiceActiveKind: send.voiceActiveKind,
    voiceProgress01: send.voiceProgress01,
    voiceBusy: send.voiceBusy,
    voiceRecording: send.voiceRecording,
    onVoiceToggle: send.onVoiceToggle,
    onVoiceEmergencyToggle: send.onVoiceEmergencyToggle,
    voiceNormalBlockedStart: send.voiceNormalBlockedStart,
    voiceEmergencyBlockedStart: send.voiceEmergencyBlockedStart,
    voiceMaxSeconds: send.voiceMaxSeconds,
    voiceEmergencyMaxSeconds: send.voiceEmergencyMaxSeconds,
    sosVoiceFollowsOnline: send.sosVoiceFollowsOnline,
    sosVoiceAwaitingSend: send.sosVoiceAwaitingSend,
  }
}
